### ISSUE TITLE
Controlling text inside the labels

### ISSUE THREAD

**Issue by priyabrat1801** [PredixDev/px-alert-label#1]
Is there a way the text inside the colored boxes can be dynamic e.g. passing through a parameter? Also, can the size of the box and color be controlled in the current state?

**Comment by dmcalpin** [comment]
i've opened a PR that allows text to be overridden: https://github.com/PredixDev/px-alert-label/pull/3
as for updating the color. you can do that just by changing the type attribute with JavaScript

**Comment by randyaskin** [comment]
Added in version 1.0.0 of the component.
