### ISSUE TITLE
Background Colors not significantly differentiated for color impaired

### ISSUE THREAD

**Issue by liqdfire** [PredixDev/px-alert-label#5]
The background colors chosen for important, warning, and error are not significantly different for an individual that has a red / green deficiency. 

These links show an approximation of the colors as a color deficient individual might see them:
http://www.colorhexa.com/e8a736
http://www.colorhexa.com/e53838
http://www.colorhexa.com/dd6b1f

**Comment by randyaskin** [comment]
The colors are all configurable using the CSS variables listed on [the API doc](https://www.predix-ui.com/#/components/px-alert-label/) - see [this guide](https://docs.predix.io/en-US/content/platform/web_application_development/predix_ui/theming-web-applications#reference_7fdaebef-0e3d-4a0c-b0f4-7ad0090cf91a) for theming Predix UI components, or you can refer to [the Polymer documentation on styling](https://www.polymer-project.org/1.0/docs/devguide/styling). While Predix has two default themes (px-theme and px-dark-theme), which will both be updated in July with some color improvements that apply to alert-label, in general we recommend creating your own high-contrast theme if your application or users have additional accessibility requirements.
