### ISSUE TITLE
badge flag

### ISSUE THREAD

**Issue by jcarbajal79** [PredixDev/px-alert-label#8]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

Expected Behavior: When setting the badge attribute to false it should display only the label with no badge.
Actual Behavior: Setting the badge attribute, regardless of the value renders the icon. It doesn't check for the value.

## Steps to reproduce the problem:

Use a px-alert-label component and se badge="false"

## Screenshots (_optional, but very helpful_):

<img width="276" alt="screen shot 2017-10-26 at 4 06 02 pm" src="https://user-images.githubusercontent.com/10677636/32081007-b206703a-ba67-11e7-8447-020459a24fc8.png">

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

https://codepen.io/anon/pen/wPwqvo?&editors=1001

**Comment by benoitjchevalier** [comment]
This is an HTML spec that boolean attribute behave that way: the presence of the attribute means "true" and its absence "false". Setting it to the value false hence confusingly means that the value is true.

https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.3.4.2
